-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.capitals
(
    id serial NOT NULL,
    country character varying(45) COLLATE pg_catalog."default",
    capital character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT capitals_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.countries
(
    id serial NOT NULL,
    country_code character(2) COLLATE pg_catalog."default",
    country_name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT countries_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.flags
(
    id serial NOT NULL,
    name character varying(45) COLLATE pg_catalog."default",
    flag text COLLATE pg_catalog."default",
    CONSTRAINT flags_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    name character varying(15) COLLATE pg_catalog."default" NOT NULL,
    colour character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.visited_countries
(
    id serial NOT NULL,
    country_code character(2) COLLATE pg_catalog."default" NOT NULL,
    user_id integer,
    CONSTRAINT visited_countries_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.world_food
(
    id serial NOT NULL,
    country character varying(45) COLLATE pg_catalog."default",
    rice_production double precision,
    wheat_production double precision,
    CONSTRAINT world_food_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.visited_countries
    ADD CONSTRAINT visited_countries_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;